version: '3'
services:
#   gateway:
#     build:
#       context: .
#       dockerfile: ./apps/GatewayDockerfile
#     container_name: gateway
#     restart: always
#     ports:
#       - 80:80
#   user:
#     build:
#       context: .
#       dockerfile: ./apps/UserDockerfile
#     container_name: user
#     restart: always

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:${MYSQL_PORT}
    volumes:
      - ./mysql:/var/lib/mysql
  redis:
    image: redis
    container_name: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:${REDIS_PORT}
    volumes:
      - ./redis:/data
